AWSTemplateFormatVersion: '2010-09-09'
Parameters:
    SNSEmail:
        Type: String
        Description: Enter email for SNS notification
Resources:
    AlertSNSTopic:
        Type: 'AWS::SNS::Topic'
        Properties:
            Subscription:
                - 
                    Endpoint:
                        Ref: SNSEmail
                    Protocol: email
Outputs:
  Logical ID:
    Description: Information about the value
    Value: Value to return
    Export:
      Name: Value to export
